import type { TickListener } from "../core/TickListener.js";
export declare class Game implements TickListener {
    private bg;
    private clouds;
    private rocks;
    private ground;
    private hero;
    private readonly bgTextures;
    private readonly rockTextures;
    private readonly obstacleTextures;
    private readonly cloudTextures;
    private currentBgIndex;
    private coins;
    private coinSpawnTimer;
    private readonly coinSpawnInterval;
    private score;
    private obstacles;
    private obstacleSpawnTimer;
    private readonly obstacleSpawnInterval;
    private isPaused;
    private isDead;
    private isGameOver;
    private flashAlpha;
    private btnUp;
    private btnDown;
    private btnPause;
    private btnResume;
    private btnSettings;
    private btnBack;
    private btnSound;
    private isSoundOn;
    private isInSettingsSubmenu;
    private heroSpeed;
    private readonly groundHeight;
    private gameSpeed;
    private readonly btnSize;
    private readonly btnMargin;
    private menuTargetScale;
    private menuCurrentScale;
    private readonly menuAnimSpeed;
    private restartDelayTimer;
    private onGameOverClickRef;
    constructor();
    init(): void;
    private createMobileButtons;
    private createMenuButtons;
    private openSettingsSubmenu;
    private toggleSound;
    private togglePause;
    private updateMenuButtonsPositions;
    private getRandomTexture;
    private changeEnvironmentOnDeath;
    private spawnCoinGroup;
    private spawnObstacle;
    private checkCollisions;
    private triggerDeath;
    private resetGame;
    private hookScoreRenderer;
    invoke(delta: number): void;
    private handleResize;
    dispose(): void;
}
//# sourceMappingURL=Game.d.ts.map